name: release

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      OUT_DIR: build/reborn2-marlin

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 200
        fetch-tags: true
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.platformio/.cache
        key: ${{ runner.os }}-pio
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PlatformIO Core
      run: |
        pip install --upgrade platformio
        export RELEASE_DATE=$(TZ=UTC date '+%Y-%m-%d_%H%M')
        echo "RELEASE_DATE=$RELEASE_DATE" >> ${GITHUB_ENV}
        export FULL_RELEASE_DATE=$(TZ=UTC date '+%Y-%m-%d %H:%M')
        echo "FULL_RELEASE_DATE=$FULL_RELEASE_DATE" >> ${GITHUB_ENV}
        export VERSION_NAME=$(git describe --tags --match="[0-9]*" --abbrev=0)-${RELEASE_DATE}
        echo "VERSION_NAME=$VERSION_NAME" >> ${GITHUB_ENV}
        mkdir -p $OUT_DIR
        cp docs/README.md $OUT_DIR
        cp CHANGELOG.md $OUT_DIR
        echo >> $OUT_DIR/README.md
        echo $VERSION_NAME >> $OUT_DIR/README.md
        SHORT_STRING_DISTRIBUTION_DATE=$RELEASE_DATE STRING_DISTRIBUTION_DATE=$FULL_RELEASE_DATE buildroot/bin/generate_version

    - name: Reborn2, stock
      run: |
        ENV=reborn2_manual
        pio run --environment $ENV
        DIR=$OUT_DIR/reborn2_manual
        mkdir $DIR
        cp .pio/build/$ENV/Robin_nano_6.bin $DIR
    - name: Reborn2, inductive sensor (zmin)
      run: |
        ENV=reborn2_inductive_zmin
        pio run --environment $ENV
        DIR=$OUT_DIR/reborn2_inductive_sensor_zmin
        mkdir $DIR
        cp .pio/build/$ENV/Robin_nano_6.bin $DIR
    - name: Reborn2, inductive sensor (runout2)
      run: |
        ENV=reborn2_inductive_runout2
        pio run --environment $ENV
        DIR=$OUT_DIR/reborn2_inductive_sensor_runout2
        mkdir $DIR
        cp .pio/build/$ENV/Robin_nano_6.bin $DIR
    - name: Reborn2, BLTouch sensor (zmin)
      run: |
        ENV=reborn2_bltouch_zmin
        pio run --environment $ENV
        DIR=$OUT_DIR/reborn2_bltouch_sensor_zmin
        mkdir $DIR
        cp .pio/build/$ENV/Robin_nano_6.bin $DIR
    - name: Reborn2, BLTouch sensor (runout2)
      run: |
        ENV=reborn2_bltouch_runout2
        pio run --environment $ENV
        DIR=$OUT_DIR/reborn2_bltouch_sensor_runout2
        mkdir $DIR
        cp .pio/build/$ENV/Robin_nano_6.bin $DIR

    - name: Upload Firmwares
      uses: actions/upload-artifact@v3
      with:
        name: reborn2-marlin-v${{ env.VERSION_NAME }}
        path: |
          ${{ env.OUT_DIR }}/*
